### ISSUE TITLE
Feature request: autoscaling for ticks and spines 

### ISSUE THREAD

**Issue by neutrinoceros** [andrewcharlesjones/plottify#1]
Seems to me this is the one thing missing right now. Thank you for doing this, it's a pretty elegant solution to a widespread problem, love it !

**Comment by andrewcharlesjones** [comment]
Good catch! I'll fix this -- should be straightforward.

And I'm glad you find it useful.

**Comment by neutrinoceros** [comment]
btw, not directly related, but I see that the GitHub repo and the PyPI page don't reference each other. I'm happy to contribute a PR to make them more discoverable if you'd like/

**Comment by andrewcharlesjones** [comment]
Sure, that would be great, thanks!

**Comment by andrewcharlesjones** [comment]
This should be fixed now -- thanks again for bringing this up
